### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'configs/users.json'

### ISSUE THREAD

**Issue by chiyan171** [cp59/ZeroHFS#1]
================================================================
Version: 1.0 (2022-10-09) (Release)
Author: 梁承樸(Liang Cheng-pu)
================================================================

Python 3.10.8
pip 22.3 from /usr/local/lib/python3.10/site-packages/pip (python 3.10)

Traceback (most recent call last):
  File "/Users/Downloads/HFS/ZeroHFS/app.py", line 72, in <module>
    reloadData()
  File "/Users/Downloads/HFS/ZeroHFS/app.py", line 60, in reloadData
    users = json.load(open("configs/users.json", "r", encoding="utf-8"))
FileNotFoundError: [Errno 2] No such file or directory: 'configs/users.json'

**Comment by chengpuliang** [comment]
I made the configuration tool and put it in the project directory. The file name is "configCreator.py". Please execute it to configure the server. After completion, the ZeroHFS server can be started.

我做了設定配置工具放在專案目錄裡，檔案名稱叫"configCreator.py"，請執行來配置伺服器，完成後即可啟動ZeroHFS伺服器。
